// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: zeta.proto

package zetapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Auth and Enrollment
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WgPublicKey   string                 `protobuf:"bytes,1,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"` // base64 Curve25519 public key
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"` // "linux" | "android"
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	PreauthKey    string                 `protobuf:"bytes,5,opt,name=preauth_key,json=preauthKey,proto3" json:"preauth_key,omitempty"` // optional; skips browser auth flow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_zeta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetPreauthKey() string {
	if x != nil {
		return x.PreauthKey
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RegisterResponse_Pending
	//	*RegisterResponse_Config
	Result        isRegisterResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_zeta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetResult() isRegisterResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RegisterResponse) GetPending() *PendingAuth {
	if x != nil {
		if x, ok := x.Result.(*RegisterResponse_Pending); ok {
			return x.Pending
		}
	}
	return nil
}

func (x *RegisterResponse) GetConfig() *NodeConfig {
	if x != nil {
		if x, ok := x.Result.(*RegisterResponse_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isRegisterResponse_Result interface {
	isRegisterResponse_Result()
}

type RegisterResponse_Pending struct {
	Pending *PendingAuth `protobuf:"bytes,1,opt,name=pending,proto3,oneof"` // interactive: open this URL
}

type RegisterResponse_Config struct {
	Config *NodeConfig `protobuf:"bytes,2,opt,name=config,proto3,oneof"` // headless preauth: here's your config
}

func (*RegisterResponse_Pending) isRegisterResponse_Result() {}

func (*RegisterResponse_Config) isRegisterResponse_Result() {}

type PendingAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`          // open in browser
	SessionKey    string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"` // poll / stream with this after auth completes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingAuth) Reset() {
	*x = PendingAuth{}
	mi := &file_zeta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingAuth) ProtoMessage() {}

func (x *PendingAuth) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingAuth.ProtoReflect.Descriptor instead.
func (*PendingAuth) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{2}
}

func (x *PendingAuth) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *PendingAuth) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MeshIp        string                 `protobuf:"bytes,2,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	CertPem       []byte                 `protobuf:"bytes,4,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"` // device certificate (PEM)
	CaPem         []byte                 `protobuf:"bytes,5,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`       // coordinator CA root (PEM)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_zeta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{3}
}

func (x *NodeConfig) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeConfig) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *NodeConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *NodeConfig) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *NodeConfig) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

// Sync Streams
// Client → Server
type SyncUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncUpdate_Endpoint
	//	*SyncUpdate_Services
	//	*SyncUpdate_Ping
	Payload       isSyncUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUpdate) Reset() {
	*x = SyncUpdate{}
	mi := &file_zeta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdate) ProtoMessage() {}

func (x *SyncUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdate.ProtoReflect.Descriptor instead.
func (*SyncUpdate) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{4}
}

func (x *SyncUpdate) GetPayload() isSyncUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncUpdate) GetEndpoint() *EndpointUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SyncUpdate_Endpoint); ok {
			return x.Endpoint
		}
	}
	return nil
}

func (x *SyncUpdate) GetServices() *ServiceUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SyncUpdate_Services); ok {
			return x.Services
		}
	}
	return nil
}

func (x *SyncUpdate) GetPing() *PingUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SyncUpdate_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isSyncUpdate_Payload interface {
	isSyncUpdate_Payload()
}

type SyncUpdate_Endpoint struct {
	Endpoint *EndpointUpdate `protobuf:"bytes,1,opt,name=endpoint,proto3,oneof"`
}

type SyncUpdate_Services struct {
	Services *ServiceUpdate `protobuf:"bytes,2,opt,name=services,proto3,oneof"`
}

type SyncUpdate_Ping struct {
	Ping *PingUpdate `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*SyncUpdate_Endpoint) isSyncUpdate_Payload() {}

func (*SyncUpdate_Services) isSyncUpdate_Payload() {}

func (*SyncUpdate_Ping) isSyncUpdate_Payload() {}

type EndpointUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // "ip:port" discovered via STUN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointUpdate) Reset() {
	*x = EndpointUpdate{}
	mi := &file_zeta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointUpdate) ProtoMessage() {}

func (x *EndpointUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointUpdate.ProtoReflect.Descriptor instead.
func (*EndpointUpdate) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{5}
}

func (x *EndpointUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EndpointUpdate) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type ServiceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Services      []*Service             `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	mi := &file_zeta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServiceUpdate) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type PingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingUpdate) Reset() {
	*x = PingUpdate{}
	mi := &file_zeta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingUpdate) ProtoMessage() {}

func (x *PingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingUpdate.ProtoReflect.Descriptor instead.
func (*PingUpdate) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{7}
}

func (x *PingUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Server → Client
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncResponse_NetworkMap
	//	*SyncResponse_Relay
	//	*SyncResponse_IceSignal
	Payload       isSyncResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_zeta_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{8}
}

func (x *SyncResponse) GetPayload() isSyncResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncResponse) GetNetworkMap() *NetworkMap {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_NetworkMap); ok {
			return x.NetworkMap
		}
	}
	return nil
}

func (x *SyncResponse) GetRelay() *RelayOffer {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Relay); ok {
			return x.Relay
		}
	}
	return nil
}

func (x *SyncResponse) GetIceSignal() *ICESignal {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_IceSignal); ok {
			return x.IceSignal
		}
	}
	return nil
}

type isSyncResponse_Payload interface {
	isSyncResponse_Payload()
}

type SyncResponse_NetworkMap struct {
	NetworkMap *NetworkMap `protobuf:"bytes,1,opt,name=network_map,json=networkMap,proto3,oneof"`
}

type SyncResponse_Relay struct {
	Relay *RelayOffer `protobuf:"bytes,2,opt,name=relay,proto3,oneof"`
}

type SyncResponse_IceSignal struct {
	IceSignal *ICESignal `protobuf:"bytes,3,opt,name=ice_signal,json=iceSignal,proto3,oneof"`
}

func (*SyncResponse_NetworkMap) isSyncResponse_Payload() {}

func (*SyncResponse_Relay) isSyncResponse_Payload() {}

func (*SyncResponse_IceSignal) isSyncResponse_Payload() {}

// Network Map
type NetworkMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Dns           *DNSConfig             `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	RelayMap      *RelayMap              `protobuf:"bytes,3,opt,name=relay_map,json=relayMap,proto3" json:"relay_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMap) Reset() {
	*x = NetworkMap{}
	mi := &file_zeta_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMap) ProtoMessage() {}

func (x *NetworkMap) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMap.ProtoReflect.Descriptor instead.
func (*NetworkMap) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkMap) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NetworkMap) GetDns() *DNSConfig {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *NetworkMap) GetRelayMap() *RelayMap {
	if x != nil {
		return x.RelayMap
	}
	return nil
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WgPublicKey   string                 `protobuf:"bytes,2,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"`
	MeshIp        string                 `protobuf:"bytes,3,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // last known "ip:port"
	Services      []*Service             `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	Online        bool                   `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_zeta_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{10}
}

func (x *Peer) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Peer) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

func (x *Peer) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *Peer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Peer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Peer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Peer) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Peer) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	AllowedUsers  []string               `protobuf:"bytes,3,rep,name=allowed_users,json=allowedUsers,proto3" json:"allowed_users,omitempty"` // user IDs; empty = node-owner only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_zeta_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{11}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

type DNSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeshDomain    string                 `protobuf:"bytes,1,opt,name=mesh_domain,json=meshDomain,proto3" json:"mesh_domain,omitempty"` // e.g. "mesh"
	DnsServer     string                 `protobuf:"bytes,2,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`    // coordinator's mesh IP as DNS server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSConfig) Reset() {
	*x = DNSConfig{}
	mi := &file_zeta_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSConfig) ProtoMessage() {}

func (x *DNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSConfig.ProtoReflect.Descriptor instead.
func (*DNSConfig) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{12}
}

func (x *DNSConfig) GetMeshDomain() string {
	if x != nil {
		return x.MeshDomain
	}
	return ""
}

func (x *DNSConfig) GetDnsServer() string {
	if x != nil {
		return x.DnsServer
	}
	return ""
}

type RelayMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*RelayServer         `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMap) Reset() {
	*x = RelayMap{}
	mi := &file_zeta_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMap) ProtoMessage() {}

func (x *RelayMap) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMap.ProtoReflect.Descriptor instead.
func (*RelayMap) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{13}
}

func (x *RelayMap) GetServers() []*RelayServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

type RelayServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayServer) Reset() {
	*x = RelayServer{}
	mi := &file_zeta_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayServer) ProtoMessage() {}

func (x *RelayServer) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayServer.ProtoReflect.Descriptor instead.
func (*RelayServer) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{14}
}

func (x *RelayServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RelayServer) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RelayServer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RelayServer) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Relay
type RelayOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayOffer) Reset() {
	*x = RelayOffer{}
	mi := &file_zeta_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOffer) ProtoMessage() {}

func (x *RelayOffer) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOffer.ProtoReflect.Descriptor instead.
func (*RelayOffer) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{15}
}

func (x *RelayOffer) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *RelayOffer) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

type ICESignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded ICE candidate or SDP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICESignal) Reset() {
	*x = ICESignal{}
	mi := &file_zeta_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICESignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICESignal) ProtoMessage() {}

func (x *ICESignal) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICESignal.ProtoReflect.Descriptor instead.
func (*ICESignal) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{16}
}

func (x *ICESignal) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *ICESignal) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *ICESignal) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Other
type ServerKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerKeyResponse) Reset() {
	*x = ServerKeyResponse{}
	mi := &file_zeta_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKeyResponse) ProtoMessage() {}

func (x *ServerKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKeyResponse.ProtoReflect.Descriptor instead.
func (*ServerKeyResponse) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{17}
}

func (x *ServerKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_zeta_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_zeta_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_zeta_proto_rawDescGZIP(), []int{18}
}

var File_zeta_proto protoreflect.FileDescriptor

const file_zeta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"zeta.proto\x12\azeta.v1\"\xa7\x01\n" +
	"\x0fRegisterRequest\x12\"\n" +
	"\rwg_public_key\x18\x01 \x01(\tR\vwgPublicKey\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vpreauth_key\x18\x05 \x01(\tR\n" +
	"preauthKey\"}\n" +
	"\x10RegisterResponse\x120\n" +
	"\apending\x18\x01 \x01(\v2\x14.zeta.v1.PendingAuthH\x00R\apending\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x13.zeta.v1.NodeConfigH\x00R\x06configB\b\n" +
	"\x06result\"I\n" +
	"\vPendingAuth\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\"\x88\x01\n" +
	"\n" +
	"NodeConfig\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\amesh_ip\x18\x02 \x01(\tR\x06meshIp\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x19\n" +
	"\bcert_pem\x18\x04 \x01(\fR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x05 \x01(\fR\x05caPem\"\xaf\x01\n" +
	"\n" +
	"SyncUpdate\x125\n" +
	"\bendpoint\x18\x01 \x01(\v2\x17.zeta.v1.EndpointUpdateH\x00R\bendpoint\x124\n" +
	"\bservices\x18\x02 \x01(\v2\x16.zeta.v1.ServiceUpdateH\x00R\bservices\x12)\n" +
	"\x04ping\x18\x03 \x01(\v2\x13.zeta.v1.PingUpdateH\x00R\x04pingB\t\n" +
	"\apayload\"E\n" +
	"\x0eEndpointUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"V\n" +
	"\rServiceUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\bservices\x18\x02 \x03(\v2\x10.zeta.v1.ServiceR\bservices\"%\n" +
	"\n" +
	"PingUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xb3\x01\n" +
	"\fSyncResponse\x126\n" +
	"\vnetwork_map\x18\x01 \x01(\v2\x13.zeta.v1.NetworkMapH\x00R\n" +
	"networkMap\x12+\n" +
	"\x05relay\x18\x02 \x01(\v2\x13.zeta.v1.RelayOfferH\x00R\x05relay\x123\n" +
	"\n" +
	"ice_signal\x18\x03 \x01(\v2\x12.zeta.v1.ICESignalH\x00R\ticeSignalB\t\n" +
	"\apayload\"\x87\x01\n" +
	"\n" +
	"NetworkMap\x12#\n" +
	"\x05peers\x18\x01 \x03(\v2\r.zeta.v1.PeerR\x05peers\x12$\n" +
	"\x03dns\x18\x02 \x01(\v2\x12.zeta.v1.DNSConfigR\x03dns\x12.\n" +
	"\trelay_map\x18\x03 \x01(\v2\x11.zeta.v1.RelayMapR\brelayMap\"\xf3\x01\n" +
	"\x04Peer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\"\n" +
	"\rwg_public_key\x18\x02 \x01(\tR\vwgPublicKey\x12\x17\n" +
	"\amesh_ip\x18\x03 \x01(\tR\x06meshIp\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12,\n" +
	"\bservices\x18\a \x03(\v2\x10.zeta.v1.ServiceR\bservices\x12\x16\n" +
	"\x06online\x18\b \x01(\bR\x06online\"V\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12#\n" +
	"\rallowed_users\x18\x03 \x03(\tR\fallowedUsers\"K\n" +
	"\tDNSConfig\x12\x1f\n" +
	"\vmesh_domain\x18\x01 \x01(\tR\n" +
	"meshDomain\x12\x1d\n" +
	"\n" +
	"dns_server\x18\x02 \x01(\tR\tdnsServer\":\n" +
	"\bRelayMap\x12.\n" +
	"\aservers\x18\x01 \x03(\v2\x14.zeta.v1.RelayServerR\aservers\"e\n" +
	"\vRelayServer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\"L\n" +
	"\n" +
	"RelayOffer\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\"e\n" +
	"\tICESignal\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"2\n" +
	"\x11ServerKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"\a\n" +
	"\x05Empty2\xc9\x01\n" +
	"\x12CoordinatorService\x12:\n" +
	"\fGetServerKey\x12\x0e.zeta.v1.Empty\x1a\x1a.zeta.v1.ServerKeyResponse\x12?\n" +
	"\bRegister\x12\x18.zeta.v1.RegisterRequest\x1a\x19.zeta.v1.RegisterResponse\x126\n" +
	"\x04Sync\x12\x13.zeta.v1.SyncUpdate\x1a\x15.zeta.v1.SyncResponse(\x010\x01B@Z>github.com/kreativethinker/zeta/controller/internal/api/zetapbb\x06proto3"

var (
	file_zeta_proto_rawDescOnce sync.Once
	file_zeta_proto_rawDescData []byte
)

func file_zeta_proto_rawDescGZIP() []byte {
	file_zeta_proto_rawDescOnce.Do(func() {
		file_zeta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zeta_proto_rawDesc), len(file_zeta_proto_rawDesc)))
	})
	return file_zeta_proto_rawDescData
}

var file_zeta_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_zeta_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: zeta.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 1: zeta.v1.RegisterResponse
	(*PendingAuth)(nil),       // 2: zeta.v1.PendingAuth
	(*NodeConfig)(nil),        // 3: zeta.v1.NodeConfig
	(*SyncUpdate)(nil),        // 4: zeta.v1.SyncUpdate
	(*EndpointUpdate)(nil),    // 5: zeta.v1.EndpointUpdate
	(*ServiceUpdate)(nil),     // 6: zeta.v1.ServiceUpdate
	(*PingUpdate)(nil),        // 7: zeta.v1.PingUpdate
	(*SyncResponse)(nil),      // 8: zeta.v1.SyncResponse
	(*NetworkMap)(nil),        // 9: zeta.v1.NetworkMap
	(*Peer)(nil),              // 10: zeta.v1.Peer
	(*Service)(nil),           // 11: zeta.v1.Service
	(*DNSConfig)(nil),         // 12: zeta.v1.DNSConfig
	(*RelayMap)(nil),          // 13: zeta.v1.RelayMap
	(*RelayServer)(nil),       // 14: zeta.v1.RelayServer
	(*RelayOffer)(nil),        // 15: zeta.v1.RelayOffer
	(*ICESignal)(nil),         // 16: zeta.v1.ICESignal
	(*ServerKeyResponse)(nil), // 17: zeta.v1.ServerKeyResponse
	(*Empty)(nil),             // 18: zeta.v1.Empty
}
var file_zeta_proto_depIdxs = []int32{
	2,  // 0: zeta.v1.RegisterResponse.pending:type_name -> zeta.v1.PendingAuth
	3,  // 1: zeta.v1.RegisterResponse.config:type_name -> zeta.v1.NodeConfig
	5,  // 2: zeta.v1.SyncUpdate.endpoint:type_name -> zeta.v1.EndpointUpdate
	6,  // 3: zeta.v1.SyncUpdate.services:type_name -> zeta.v1.ServiceUpdate
	7,  // 4: zeta.v1.SyncUpdate.ping:type_name -> zeta.v1.PingUpdate
	11, // 5: zeta.v1.ServiceUpdate.services:type_name -> zeta.v1.Service
	9,  // 6: zeta.v1.SyncResponse.network_map:type_name -> zeta.v1.NetworkMap
	15, // 7: zeta.v1.SyncResponse.relay:type_name -> zeta.v1.RelayOffer
	16, // 8: zeta.v1.SyncResponse.ice_signal:type_name -> zeta.v1.ICESignal
	10, // 9: zeta.v1.NetworkMap.peers:type_name -> zeta.v1.Peer
	12, // 10: zeta.v1.NetworkMap.dns:type_name -> zeta.v1.DNSConfig
	13, // 11: zeta.v1.NetworkMap.relay_map:type_name -> zeta.v1.RelayMap
	11, // 12: zeta.v1.Peer.services:type_name -> zeta.v1.Service
	14, // 13: zeta.v1.RelayMap.servers:type_name -> zeta.v1.RelayServer
	18, // 14: zeta.v1.CoordinatorService.GetServerKey:input_type -> zeta.v1.Empty
	0,  // 15: zeta.v1.CoordinatorService.Register:input_type -> zeta.v1.RegisterRequest
	4,  // 16: zeta.v1.CoordinatorService.Sync:input_type -> zeta.v1.SyncUpdate
	17, // 17: zeta.v1.CoordinatorService.GetServerKey:output_type -> zeta.v1.ServerKeyResponse
	1,  // 18: zeta.v1.CoordinatorService.Register:output_type -> zeta.v1.RegisterResponse
	8,  // 19: zeta.v1.CoordinatorService.Sync:output_type -> zeta.v1.SyncResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_zeta_proto_init() }
func file_zeta_proto_init() {
	if File_zeta_proto != nil {
		return
	}
	file_zeta_proto_msgTypes[1].OneofWrappers = []any{
		(*RegisterResponse_Pending)(nil),
		(*RegisterResponse_Config)(nil),
	}
	file_zeta_proto_msgTypes[4].OneofWrappers = []any{
		(*SyncUpdate_Endpoint)(nil),
		(*SyncUpdate_Services)(nil),
		(*SyncUpdate_Ping)(nil),
	}
	file_zeta_proto_msgTypes[8].OneofWrappers = []any{
		(*SyncResponse_NetworkMap)(nil),
		(*SyncResponse_Relay)(nil),
		(*SyncResponse_IceSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zeta_proto_rawDesc), len(file_zeta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zeta_proto_goTypes,
		DependencyIndexes: file_zeta_proto_depIdxs,
		MessageInfos:      file_zeta_proto_msgTypes,
	}.Build()
	File_zeta_proto = out.File
	file_zeta_proto_goTypes = nil
	file_zeta_proto_depIdxs = nil
}
